// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk09hF5I4yP9qMjvO9RheGVqwHabNnIKQ',
    appId: '1:27125723393:android:7cf57b420e426fa914ab00',
    messagingSenderId: '27125723393',
    projectId: 'dbs-app-70351',
    storageBucket: 'dbs-app-70351.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCswsmox2Ijq5hgIKjCEo5TSgetjQGitxY',
    appId: '1:27125723393:ios:6ddb46d506acfdf414ab00',
    messagingSenderId: '27125723393',
    projectId: 'dbs-app-70351',
    storageBucket: 'dbs-app-70351.appspot.com',
    androidClientId: '27125723393-1u0catpnnmi80buurdks3vl3e3c9iu8t.apps.googleusercontent.com',
    iosClientId: '27125723393-l8nu8o4rmatqfc4oslbkc7h1q3smq93u.apps.googleusercontent.com',
    iosBundleId: 'com.cusDbs.cusDbsApplication',
  );
}
